Importing the Packages we will be using

In [67]:
import numpy as np # imports package numpy with alias 'np'
from numpy import random
import math # imports package math

Defining two list variables

In [68]:
list1 = [2, 3, 4, 6, 7, 8]
list2 = [45, 34, 23, 45, 12, 3]

In [69]:
list1 + list2

[2, 3, 4, 6, 7, 8, 45, 34, 23, 45, 12, 3]

Using a for loop to add the two lists

In [70]:
total = []

for num in list1:
    s = num + list2[list1.index(num)]
    total.append(s)

total

[47, 37, 27, 51, 19, 11]

Defining my two lists as arrays

In [71]:
num1 = np.array(list1)
num2 = np.array(list2)

Adding the two arrays.
This is much more efficient that doing a for loop of two lists.

In [72]:
totalarr = num1 + num2

Picking index 2 of the array

In [73]:
totalarr[2]

27

Slicing the array from elements at index 2 to 5

In [74]:
totalarr[2:5]

array([27, 51, 19])

Slicing the array up intil index 5 inclusive

In [75]:
totalarr[:5]

array([47, 37, 27, 51, 19])

Slicing the array from element at index 2 onwards

In [76]:
totalarr[2:]

array([27, 51, 19, 11])

Checks if each value is is true or false against the condition

In [77]:
totalarr > 29

array([ True,  True, False,  True, False, False])

In [78]:
totalarr[[True,  True, False,  True, False, False]]

array([47, 37, 51])

In [79]:
totalarr[totalarr > 29]

array([47, 37, 51])

Checks the dimension of the array

In [80]:
totalarr.ndim

1

Creating a 2D array

In [81]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

arr[row, column]

In [82]:
arr[0, 2]

3

Adds all numbers in the array

In [83]:
arr.sum()

21

Adds the numbers in all rows and column index 2

In [84]:
arr[:, 2].sum()

9

In [85]:
np.sum(arr[:, 2])

9

Sorts the array

In [86]:
totalarr.sort()
totalarr

array([11, 19, 27, 37, 47, 51])

Gives a random number between 0 and 1

In [87]:
random.rand()

0.44907988587672787